// Generated by gencpp from file mission_planner2/UAVState.msg
// DO NOT EDIT!


#ifndef MISSION_PLANNER2_MESSAGE_UAVSTATE_H
#define MISSION_PLANNER2_MESSAGE_UAVSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mavros_msgs/State.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/TwistStamped.h>

namespace mission_planner2
{
template <class ContainerAllocator>
struct UAVState_
{
  typedef UAVState_<ContainerAllocator> Type;

  UAVState_()
    : UAV_state()
    , UAV_pose()
    , UAV_velocity_body()  {
    }
  UAVState_(const ContainerAllocator& _alloc)
    : UAV_state(_alloc)
    , UAV_pose(_alloc)
    , UAV_velocity_body(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mavros_msgs::State_<ContainerAllocator>  _UAV_state_type;
  _UAV_state_type UAV_state;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _UAV_pose_type;
  _UAV_pose_type UAV_pose;

   typedef  ::geometry_msgs::TwistStamped_<ContainerAllocator>  _UAV_velocity_body_type;
  _UAV_velocity_body_type UAV_velocity_body;





  typedef boost::shared_ptr< ::mission_planner2::UAVState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mission_planner2::UAVState_<ContainerAllocator> const> ConstPtr;

}; // struct UAVState_

typedef ::mission_planner2::UAVState_<std::allocator<void> > UAVState;

typedef boost::shared_ptr< ::mission_planner2::UAVState > UAVStatePtr;
typedef boost::shared_ptr< ::mission_planner2::UAVState const> UAVStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mission_planner2::UAVState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mission_planner2::UAVState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mission_planner2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geographic_msgs': ['/opt/ros/kinetic/share/geographic_msgs/cmake/../msg'], 'mission_planner2': ['/home/lihai/UAV/UAV2_ws/src/mission_planner2/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'mavros_msgs': ['/opt/ros/kinetic/share/mavros_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'uuid_msgs': ['/opt/ros/kinetic/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mission_planner2::UAVState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mission_planner2::UAVState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mission_planner2::UAVState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mission_planner2::UAVState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mission_planner2::UAVState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mission_planner2::UAVState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mission_planner2::UAVState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eae4a5d2f481a147e42719a9b469620f";
  }

  static const char* value(const ::mission_planner2::UAVState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeae4a5d2f481a147ULL;
  static const uint64_t static_value2 = 0xe42719a9b469620fULL;
};

template<class ContainerAllocator>
struct DataType< ::mission_planner2::UAVState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mission_planner2/UAVState";
  }

  static const char* value(const ::mission_planner2::UAVState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mission_planner2::UAVState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/State UAV_state\n\
geometry_msgs/PoseStamped UAV_pose\n\
geometry_msgs/TwistStamped UAV_velocity_body\n\
================================================================================\n\
MSG: mavros_msgs/State\n\
# Current autopilot state\n\
#\n\
# Known modes listed here:\n\
# http://wiki.ros.org/mavros/CustomModes\n\
#\n\
# For system_status values\n\
# see https://mavlink.io/en/messages/common.html#MAV_STATE\n\
#\n\
\n\
std_msgs/Header header\n\
bool connected\n\
bool armed\n\
bool guided\n\
bool manual_input\n\
string mode\n\
uint8 system_status\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TwistStamped\n\
# A twist with reference coordinate frame and timestamp\n\
Header header\n\
Twist twist\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::mission_planner2::UAVState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mission_planner2::UAVState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.UAV_state);
      stream.next(m.UAV_pose);
      stream.next(m.UAV_velocity_body);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UAVState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mission_planner2::UAVState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mission_planner2::UAVState_<ContainerAllocator>& v)
  {
    s << indent << "UAV_state: ";
    s << std::endl;
    Printer< ::mavros_msgs::State_<ContainerAllocator> >::stream(s, indent + "  ", v.UAV_state);
    s << indent << "UAV_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.UAV_pose);
    s << indent << "UAV_velocity_body: ";
    s << std::endl;
    Printer< ::geometry_msgs::TwistStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.UAV_velocity_body);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MISSION_PLANNER2_MESSAGE_UAVSTATE_H
